### ISSUE TITLE
Bind for 0.0.0.0:8080 failed: port is already allocated

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru-installer#6]
Tsuru api is not being installed due to port already allocated.

Port 8080 is in use by docker-proxy

```
Status: Downloaded newer image for tsuru/api:latest
Error installing Tsuru API
Error: API error (500): {"message":"driver failed programming external connectivity on endpoint tsuru (1083dc22feeec69afc7c2412f290cf057909c548a61e158e1c53c089031b25e8): Bind for 0.0.0.0:8080 failed: port is already allocated"}
```

**Comment by andrestc** [comment]
Hi, this project has been deprecated. You should use the tsuru installer that comes bundled with the tsuru client, as stated in the [docs](https://docs.tsuru.io/master/experimental/installer.html)
